version: '3'

services:
    haproxy:
        build: ./haproxy
        ports:
            - "702:443"
            - "602:80"
    nginx1:
        build: ./nginx1
        ports:
            - "502:80"
            - "402:443"
        restart: always

        volumes:
            - "./logs/error.log:/var/log/nginx/error.log"
            - "./logs/access.log:/var/log/nginx/access.log"
            - "./nginx1/default.conf:/etc/nginx/conf.d/default.conf"
            - "./source:/var/www/html"
        depends_on:
            - mysql_master
            - php
    nginx2:
        build: ./nginx2
        ports:
            - "302:80"
            - "202:443"
        restart: always

        volumes:
            - "./logs/error.log:/var/log/nginx/error.log"
            - "./logs/access.log:/var/log/nginx/access.log"
            - "./nginx2/default.conf:/etc/nginx/conf.d/default.conf"
            - "./source:/var/www/html"
        depends_on:
            - mysql_master
            - php
    mysql_master:
        build: ./mysql_master
        ports:
            - "802:3306"
        volumes:
            - "./data_master:/var/lib/mysql"
        restart: always

    mysql_slave:
        build: ./mysql_slave
        ports:
            - "902:3306"
        volumes:
            - "./data_slave:/var/lib/mysql"
        restart: always
        depends_on:
            - mysql_master

    redis:
        build: ./redis
        ports:
            - '1002:6379'

    memcached:
        build: ./memcached
        ports:
            - '1102:11211'

    php:
        build: ./php
        restart: always
        volumes:
            - "./php/php.ini:/usr/local/etc/php/conf.d/php.ini"
            - "./source:/var/www/html"
